### ISSUE TITLE
Quick Insert

### ISSUE THREAD

**Issue by magician11** [froala/react-froala-wysiwyg#10]
A couple of questions

## 1

When I place the cursor in the editor, the quick insert button appears.

However, once I start typing, or place the cursor on a new line, that quick insert button no longer appears.

It seems it should appear on every line?

> The quick insert button will appear when you have focus on an empty line.

https://www.froala.com/wysiwyg-editor/examples/quick-insert

## 2

If we didn't want the quick insert to appear at all, what do we do? Setting quickInsertButtons` to **null** or **[]** still shows the + icon, but with an empty list.

**Comment by stefanneculai** [comment]
Hi @magician11! This has been fixed recently. Please make sure you're using the V2.3.5 version. If you want to disable the quick-insert, all you should do is not to include the plugin at all.

**Comment by magician11** [comment]
Hi @stefanneculai 

We have `"react-froala-wysiwyg": "^2.3.5-2",` installed. And it still doesn't seem to be working properly.

I'm still not sure how to disable the quick insert button.

We still want the image plugin, just for it not to show the quick insert button menu.

![screen shot 2016-11-15 at 5 53 07 pm](https://cloud.githubusercontent.com/assets/3735849/20303103/71600d68-ab5c-11e6-99cc-1742fdd50e67.png)

Are you saying to disable some plugin using [this option](https://www.froala.com/wysiwyg-editor/docs/options#pluginsEnabled)?

Thanks.
