### ISSUE TITLE
v2.9.5 - Module not found: Error: Can't resolve 'react-froala-wysiwyg'

### ISSUE THREAD

**Issue by mcarlotta** [froala/react-froala-wysiwyg#136]
Seems like the same issue has raised as experienced with v2.9.4 now with v2.9.5

**Comment by daogurtsov** [comment]
for me issue begins from v2.9.3

**Comment by Snivik** [comment]
> for me issue begins from v2.9.3

The latest version I've managed to get this issue resolved with is 2.9.3. 

For people who just signed up and automatically are using 2.9.4 and up, just change the version to 2.9.3 in package.json (without arrow up), and it should fix the issue

**Comment by stefanneculai** [comment]
Just published 2.9.5-1. Should be fixed - sorry for the trouble.

**Comment by kristian-puccio** [comment]
@stefanneculai this isn't fixed.

Seems like the index.js file is missing, maybe something has changed with the TS setup?

**Comment by amelekhin** [comment]
@stefanneculai Hi! After I updated our app from Webpack 3 to Webpack 4, this problem has occurred. It first occurred under 2.9.2, but persists in 2.9.4, 2.9.5 and 2.9.5-1, too. Would you give any suggestions on how to fix this problem?

**Comment by drpiou** [comment]
Same here, and it's annoying... For me the "only last working version" is `2.9.4-1`, reinstalled with `npm i -S react-froala-wysiwyg@2.9.4-1`

**Comment by karanjariwala** [comment]
Still facing this issue on 2.9.6.  :(
Can anyone please help. We are on Webpack 4.

**Comment by karanjariwala** [comment]
> Just published 2.9.5-1. Should be fixed - sorry for the trouble.

This is still happening for 2.9.6.

**Comment by mbensch** [comment]
@stefanneculai Still happening in 2.9.6. We're not ready to move on to 3.x just yet. Can you please fix this asap or give me a hint on how to work around it. We're severely blocked by this. Thank you!

**Comment by jyhong666** [comment]
> @stefanneculai Still happening in 2.9.6. We're not ready to move on to 3.x just yet. Can you please fix this asap or give me a hint on how to work around it. We're severely blocked by this. Thank you!
+1
